ALTER TABLE shopping_items
ADD COLUMN category TEXT NOT NULL DEFAULT 'OTHER'
CHECK (category IN (
  'DAIRY', 'BAKERY', 'FRUIT', 'VEGETABLES', 'MEAT', 'FISH', 'EGGS', 'DRINKS', 'WATER',
  'COFFEE_TEA', 'PASTA_RICE', 'PANTRY', 'CANNED', 'FROZEN', 'SWEETS', 'CLEANING',
  'HYGIENE', 'PAPER', 'PETS', 'OTHER'
));

ALTER TABLE product_preferences
ADD COLUMN category TEXT
CHECK (category IS NULL OR category IN (
  'DAIRY', 'BAKERY', 'FRUIT', 'VEGETABLES', 'MEAT', 'FISH', 'EGGS', 'DRINKS', 'WATER',
  'COFFEE_TEA', 'PASTA_RICE', 'PANTRY', 'CANNED', 'FROZEN', 'SWEETS', 'CLEANING',
  'HYGIENE', 'PAPER', 'PETS', 'OTHER'
));
